Add article model
philipd97/alpha_blog pull request #4
Opened 2021-09-16 15:30 UTC by philipd97

- add Article model
- using rails console to do `CRUD` operation

2021-09-16 16:51 UTC, tlkiong commented
what kind of review do you expect me to have here?

2021-09-18 04:28 UTC, philipd97 commented
😅 ahh, ok I'll merge it straight

2021-09-18 09:36 UTC, philipd97 commented
@tlkiong I added the validation for this model, is review required?

2021-09-18 09:58 UTC, tlkiong requested changes

2021-09-18 09:58 UTC, tlkiong commented on app/models/article.rb
> +  validates :description, presence: true, length: { minimum: 6, maximum: 100 }
use `validates_presence_of`

2021-09-19 09:37 UTC, philipd97 commented on app/models/article.rb
> +  validates :description, presence: true, length: { minimum: 6, maximum: 100 }
> use `validates_presence_of`

Is this is the preferred way when want to validates using presence? Is there any difference if uses `validates :attribute_name, presence: true` ? 

I stumble upon rails style guide recommends to use `validates` if specifying the length 

https://github.com/rubocop/rails-style-guide#new-style-validations

2021-09-19 12:41 UTC, tlkiong commented on app/models/article.rb
> +  validates :description, presence: true, length: { minimum: 6, maximum: 100 }
validates_presence_of <= only validate presence
validates <= validates more than presence on one line

2021-09-19 12:41 UTC, tlkiong approved these changes

2021-09-19 12:48 UTC, LeeRenJie approved these changes

2021-09-19 12:52 UTC, merged