Unit testing for Category model
philipd97/alpha_blog pull request #88
Opened 2022-01-15 09:51 UTC by philipd97

- create and migrate Category model
- write unit test for Category model (test on validations)

2022-01-15 14:40 UTC, tlkiong requested changes

2022-01-15 14:40 UTC, tlkiong commented on db/migrate/20220111165038_create_categories.rb
> +      t.string :name
Why is there no validation here?
eg: presence

2022-01-15 14:40 UTC, tlkiong commented on test/models/category_test.rb
> +  test "name should not be too long" do
This is a bad test case description. You have very specific max char limit. Test on the max char limit.

2022-01-15 14:40 UTC, tlkiong commented on test/models/category_test.rb
> +  test "name should not be too short" do
This is a bad test case description. You have very specific min char limit. Test on the min char limit.

2022-01-16 04:36 UTC, philipd97 commented on db/migrate/20220111165038_create_categories.rb
> +      t.string :name
is there validation for limit of characters from minimum to maximum instead of limiting max length only? ```:limit => 25'```

2022-01-16 04:44 UTC, tlkiong commented on db/migrate/20220111165038_create_categories.rb
> +      t.string :name
That is application level validation.
This here is db validation.
Always have db validation so that later if you use other sources (not this rails app) to access & add data, the validation is still in place

2022-01-16 04:45 UTC, tlkiong requested changes

2022-01-16 04:45 UTC, tlkiong commented on db/migrate/20210916092238_create_articles.rb
> +      t.text :description, :unique => true, :null => false
Why is this unique?

2022-01-16 05:08 UTC, philipd97 commented on db/migrate/20210916092238_create_articles.rb
> +      t.text :description, :unique => true, :null => false
Sorry mislook with other model

2022-01-16 10:32 UTC, tlkiong approved these changes

2022-01-16 11:03 UTC, philipd97 commented on db/migrate/20220111165038_create_categories.rb
> +      t.string :name
So let's say I change the db like adding a new table called SuperUser, how does Rails sync with new updated db? Do I need to generate a migration file in Rails?

2022-01-16 12:11 UTC, merged

2022-01-16 12:48 UTC, tlkiong commented on db/migrate/20220111165038_create_categories.rb
> +      t.string :name
How do you make a change in the db?
*Since you merge this already, let's bring this discussion to a trello card