Functional test for Category controller
philipd97/alpha_blog pull request #89
Opened 2022-01-15 09:54 UTC by philipd97

- generate test file using rails command
- add routes for Categories
- create CategoriesController along with routes actions
- define create action in CategoriesController
- write test for CategoriesController

2022-01-15 14:43 UTC, tlkiong requested changes

2022-01-15 14:43 UTC, tlkiong commented on app/controllers/categories_controller.rb
> +      render 'new'
No error if fail?

2022-01-15 14:43 UTC, tlkiong commented on test/controllers/categories_controller_test.rb
> +    @category = Category.create(name: "Sports")
This seems to be only used in `show` spec. Why put it here?

2022-01-15 14:43 UTC, tlkiong commented on test/system/categories_test.rb
> +  test "creating a Category" do
huh? No need to input anything can create category?

2022-01-16 04:23 UTC, philipd97 commented on test/controllers/categories_controller_test.rb
> +    @category = Category.create(name: "Sports")
Is it good idea to put it in `setup` even if only `show` is using? I'm thinking of to follow the other format in test model where all the setting up of instance is put in `setup`

2022-01-16 04:23 UTC, philipd97 commented on test/system/categories_test.rb
> +  test "creating a Category" do
Em, this is generated by rails command, not using this yet. Should I remove it?

2022-01-16 04:32 UTC, philipd97 commented on app/controllers/categories_controller.rb
> +      render 'new'
The error is using back from the `shared/errors` partial, render from `new` of category

Snippet here:
https://github.com/philipd97/alpha_blog/pull/89/files#diff-4f030d998256b17b58b6b304d0f3a78999b354170b7ef2537c2db81285dbebf7R7-R21

2022-01-16 04:43 UTC, tlkiong commented on test/controllers/categories_controller_test.rb
> +    @category = Category.create(name: "Sports")
No it is note. Putting here means for every method that is in this spec, it will create a Category object & data in the db. If its just one file, the impact is not a lot. However, if we make this so that everyone those it, little bit will all add up to a lot then all of a sudden, your spec became slower by 1 hour.

2022-01-16 04:43 UTC, tlkiong commented on test/system/categories_test.rb
> +  test "creating a Category" do
Don't put code you don't use in the PR

2022-01-16 12:46 UTC, tlkiong approved these changes

2022-01-16 12:57 UTC, merged